export const ADD_BOOKING = 'ADD_BOOKING';
export const INITIALIZE_BOOKINGS = 'INITIALIZE_BOOKINGS';
export const SEARCH_BOOKING = 'SEARCH_BOOKING';
export const SELECT_DAY = 'SELECT_DAY';
export const SELECT_BOOKING_CLOSEST_TO = 'SELECT_BOOKING_CLOSEST_TO';
