export const ADD_BOOKING = 'ADD_BOOKING';
export const INITIALIZE_BOOKINGS = 'INITIALIZE_BOOKINGS';
export const SEARCH_BOOKING = 'SEARCH_BOOKING';
export const SELECT_DAY = 'SELECT_DAY';
export const SELECT_DAY_BOOKING_CLOSEST_TO = 'SELECT_DAY_BOOKING_CLOSEST_TO';
export const SET_CALENDAR_CURRENT = 'SET_CALENDAR_CURRENT';
export const SET_MENU_OPEN = 'SET_MENU_OPEN';
export const TOGGLE_ADD = 'TOGGLE_ADD'
export const TOGGLE_CALENDAR = 'TOGGLE_CALENDAR';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';


